### ISSUE TITLE
Shape mismatch, 825 != 196

### ISSUE THREAD

**Issue by Henry-Bi** [CandiceD17/Bottleneck-Transformers-for-Visual-Recognition#1]
Hi, there is some wrong with me when i took your code into the maskrcnn_benchmark/modeling/backbone/resnet

**Comment by Henry-Bi** [comment]
`if  out_channels == 2048:
                    self.conv2 = MHSA(
                      dim = 512,
                      fmap_size = (14,14),
                      heads = 4,
                      dim_qk = 128,
                      dim_v = 128,
                      rel_pos_emb = True
                )
                    # print(self.conv2)
                    # nn.init.zeros_(self.conv2.weight)

            else :
                    self.conv2 = Conv2d(
                      bottleneck_channels,
                      bottleneck_channels,
                      kernel_size=3,
                      stride=stride_3x3,
                      padding=dilation,
                      bias=False,
                      groups=num_groups,
                      dilation=dilation
                  )
                    nn.init.kaiming_uniform_(self.conv2.weight, a=1)`

**Comment by CandiceD17** [comment]
You may use the wrong parameters for fmap_size, which should be a tuple of (Height, Width) of your input feature map. I think 825 != 196 (which is 14 * 14) is incurred when we try to unfold the feature map.

**Comment by CarlBhy** [comment]
> You may use the wrong parameters for fmap_size, which should be a tuple of (Height, Width) of your input feature map. I think 825 != 196 (which is 14 * 14) is incurred when we try to unfold the feature map.

**Comment by Henry-Bi** [comment]
> You may use the wrong parameters for fmap_size, which should be a tuple of (Height, Width) of your input feature map. I think 825 != 196 (which is 14 * 14) is incurred when we try to unfold the feature map.

thanks a lot! I have solved this problem.The reason for this error is that the fixed parameter famp_size set by the source code does not match the size of the image processed when I use this code.
